name: GitHub Actions CI pipeline yaml met quality gates

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  # ToDo: App om door quality gates te halen builden

  linter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 'lts/*'

      - name: Install ESLint
        run: npx eslint --version

      - name: Install dependencies
        run: npm install

      - name: Run ESLint
        run: npx eslint .

  playwright-workflow:
    uses: ./playwright.yml

  trivy-scan:
    runs-on: ubuntu-latest
    needs: playwright-workflow
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 'lts/*'

      - name: Run Trivy security scan
        uses: aquasecurity/trivy-action@0.28.0
        with:
          scan-type: fs
          scan-ref: .
          format: table

  slack-notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Slack Notification
        uses: slackapi/slack-github-action@v2.2.1
        with:
          payload-delimiter: "_"
          webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
          webhook-type: webhook-trigger
